# Generated by Django 6.0.3 on 2026-04-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pizza', models.CharField(max_length=100)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Recebido', 'Recebido'), ('Em preparo', 'Em preparo'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], default='Recebido', max_length=50)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedido')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.RESTRICT, to='app.produto')),
            ],
            options={
                'db_table': 'item_pedido',
            },
        ),
    ]
